git actions

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Deploy to Azure VM
+name: Deploy Docker App to Azure VM
 
 on:
   push:
@@ -7,18 +7,68 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
+
     steps:
+      # Step 1: Get latest repository code
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Deploy via SSH
+      # Step 2: Copy project files to VM
+      - name: Copy files to Azure VM
+        uses: appleboy/scp-action@v0.1.7
+        with:
+          host: ${{ secrets.VM_IP_ADDRESS }}
+          username: azureuser
+          key: ${{ secrets.AZURE_VM_SSH_KEY }}
+          source: "./*"
+          target: "/home/azureuser/myapp"
+
+      # Step 3: Connect to VM and deploy container
+      - name: Deploy Docker Container
         uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{ secrets.VM_IP_ADDRESS }}
           username: azureuser
           key: ${{ secrets.AZURE_VM_SSH_KEY }}
           script: |
-            cd /var/www/myapp
-            git pull origin main
-            npm install
-            pm2 restart all
+
+            echo "Checking Docker installation..."
+
+            # install Docker if missing
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing Docker..."
+
+              sudo apt update
+              sudo apt install docker.io -y
+
+              sudo systemctl start docker
+              sudo systemctl enable docker
+
+              sudo usermod -aG docker azureuser
+            else
+              echo "Docker already installed"
+            fi
+
+            # go to project directory
+           
+            cd /home/azureuser/myapp
+
+            echo "Stopping old container if exists..."
+
+            docker stop myapp || true
+            docker rm myapp || true
+
+            echo "Building Docker image..."
+
+            docker build -t myapp .
+
+            echo "Running new container..."
+
+            docker run -d \
+              --name myapp \
+              -p 80:3000 \
+              --restart unless-stopped \
+              myapp
+
+            echo "Deployment finished successfully!"
